"""Curated database of common free/consumer email provider domains.

This is the single source of truth for "free email provider" detection
(used by both the email classifier in this package and the enrichment
filter in ``core.utils.email_domain``).

Maintenance:
    - Add new domains lowercase, without a leading ``@`` or dot, in the
      region/provider group where they belong (create a new group with a
      comment if needed).
    - Only list consumer/free mailbox providers here. Disposable or
      throwaway domains (mailinator.com, 10minutemail.com, ...) are NOT
      tracked in this file - they come from the third-party
      ``disposable-email-domains`` package and are tagged separately.
    - Keep entries to registrable domains customers actually use in
      their addresses (e.g. ``gmx.de``), not marketing domains.
    - This module must stay importable without Django settings (see the
      package docstring).
"""

FREE_EMAIL_DOMAINS: frozenset[str] = frozenset(
    {
        # --- Google ---
        "gmail.com",
        "googlemail.com",
        # --- Microsoft (Outlook / Hotmail / Live / MSN) ---
        "outlook.com",
        "outlook.at",
        "outlook.be",
        "outlook.cl",
        "outlook.co.id",
        "outlook.co.il",
        "outlook.co.nz",
        "outlook.co.uk",
        "outlook.co.th",
        "outlook.com.ar",
        "outlook.com.au",
        "outlook.com.br",
        "outlook.com.gr",
        "outlook.com.tr",
        "outlook.com.vn",
        "outlook.cz",
        "outlook.de",
        "outlook.dk",
        "outlook.es",
        "outlook.fr",
        "outlook.hu",
        "outlook.ie",
        "outlook.in",
        "outlook.it",
        "outlook.jp",
        "outlook.kr",
        "outlook.lv",
        "outlook.my",
        "outlook.ph",
        "outlook.pt",
        "outlook.sa",
        "outlook.sg",
        "outlook.sk",
        "hotmail.com",
        "hotmail.be",
        "hotmail.ca",
        "hotmail.ch",
        "hotmail.co.il",
        "hotmail.co.jp",
        "hotmail.co.nz",
        "hotmail.co.th",
        "hotmail.co.uk",
        "hotmail.com.ar",
        "hotmail.com.au",
        "hotmail.com.br",
        "hotmail.com.tr",
        "hotmail.cz",
        "hotmail.de",
        "hotmail.dk",
        "hotmail.es",
        "hotmail.fi",
        "hotmail.fr",
        "hotmail.gr",
        "hotmail.hu",
        "hotmail.it",
        "hotmail.my",
        "hotmail.nl",
        "hotmail.no",
        "hotmail.ph",
        "hotmail.pt",
        "hotmail.se",
        "hotmail.sg",
        "live.com",
        "live.at",
        "live.be",
        "live.ca",
        "live.cl",
        "live.cn",
        "live.co.uk",
        "live.com.ar",
        "live.com.au",
        "live.com.mx",
        "live.com.pt",
        "live.de",
        "live.dk",
        "live.fi",
        "live.fr",
        "live.ie",
        "live.in",
        "live.it",
        "live.jp",
        "live.nl",
        "live.no",
        "live.ru",
        "live.se",
        "msn.com",
        # --- Yahoo ---
        "yahoo.com",
        "yahoo.at",
        "yahoo.be",
        "yahoo.ca",
        "yahoo.co.id",
        "yahoo.co.il",
        "yahoo.co.in",
        "yahoo.co.jp",
        "yahoo.co.kr",
        "yahoo.co.nz",
        "yahoo.co.th",
        "yahoo.co.uk",
        "yahoo.com.ar",
        "yahoo.com.au",
        "yahoo.com.br",
        "yahoo.com.cn",
        "yahoo.com.hk",
        "yahoo.com.mx",
        "yahoo.com.my",
        "yahoo.com.ph",
        "yahoo.com.sg",
        "yahoo.com.tr",
        "yahoo.com.tw",
        "yahoo.com.vn",
        "yahoo.de",
        "yahoo.dk",
        "yahoo.es",
        "yahoo.fr",
        "yahoo.gr",
        "yahoo.ie",
        "yahoo.in",
        "yahoo.it",
        "yahoo.nl",
        "yahoo.no",
        "yahoo.pl",
        "yahoo.pt",
        "yahoo.ro",
        "yahoo.se",
        "ymail.com",
        "rocketmail.com",
        # --- Apple ---
        "icloud.com",
        "me.com",
        "mac.com",
        "privaterelay.appleid.com",  # Apple Hide My Email
        # --- Privacy-focused (Proton, Tuta, ...) ---
        "proton.me",
        "protonmail.com",
        "protonmail.ch",
        "pm.me",
        "tutanota.com",
        "tutanota.de",
        "tutamail.com",
        "tuta.io",
        "tuta.com",
        "keemail.me",
        "posteo.de",
        "posteo.net",
        "mailbox.org",
        "disroot.org",
        "mailfence.com",
        "runbox.com",
        "countermail.com",
        "hushmail.com",
        # --- Other global providers ---
        "aol.com",
        "aim.com",
        "mail.com",
        "email.com",
        "usa.com",
        "myself.com",
        "consultant.com",
        "post.com",
        "europe.com",
        "gmx.com",
        "gmx.net",
        "gmx.de",
        "gmx.at",
        "gmx.ch",
        "gmx.us",
        "zoho.com",
        "zohomail.com",
        "zohomail.eu",
        "zohomail.in",
        "fastmail.com",
        "fastmail.fm",
        "hey.com",
        "inbox.com",
        "hubspot-free.com",
        "duck.com",  # DuckDuckGo Email Protection
        "simplelogin.com",
        "skiff.com",
        # --- Russia / CIS ---
        "yandex.com",
        "yandex.ru",
        "yandex.by",
        "yandex.kz",
        "yandex.ua",
        "ya.ru",
        "mail.ru",
        "bk.ru",
        "inbox.ru",
        "list.ru",
        "internet.ru",
        "rambler.ru",
        "lenta.ru",
        "ukr.net",
        "i.ua",
        "meta.ua",
        # --- China ---
        "qq.com",
        "vip.qq.com",
        "foxmail.com",
        "163.com",
        "126.com",
        "yeah.net",
        "vip.163.com",
        "vip.126.com",
        "sina.com",
        "sina.cn",
        "sina.com.cn",
        "sohu.com",
        "aliyun.com",
        "139.com",
        "189.cn",
        "wo.cn",
        "tom.com",
        "21cn.com",
        # --- Korea ---
        "naver.com",
        "daum.net",
        "hanmail.net",
        "nate.com",
        "korea.com",
        # --- Japan ---
        "docomo.ne.jp",
        "ezweb.ne.jp",
        "softbank.ne.jp",
        "i.softbank.jp",
        "au.com",
        "nifty.com",
        "biglobe.ne.jp",
        "excite.co.jp",
        # --- India / South Asia ---
        "rediffmail.com",
        "rediff.com",
        "indiatimes.com",
        "sify.com",
        # --- Germany / Austria / Switzerland ---
        "web.de",
        "t-online.de",
        "freenet.de",
        "arcor.de",
        "online.de",
        "emailn.de",
        "bluewin.ch",
        "sunrise.ch",
        "a1.net",
        "chello.at",
        # --- France / Belgium ---
        "orange.fr",
        "wanadoo.fr",
        "laposte.net",
        "free.fr",
        "sfr.fr",
        "neuf.fr",
        "bbox.fr",
        "numericable.fr",
        "aliceadsl.fr",
        "voila.fr",
        "skynet.be",
        "telenet.be",
        # --- Italy ---
        "libero.it",
        "virgilio.it",
        "tiscali.it",
        "alice.it",
        "tin.it",
        "fastwebnet.it",
        "email.it",
        "inwind.it",
        # --- Spain / Portugal ---
        "telefonica.net",
        "movistar.es",
        "ono.com",
        "sapo.pt",
        # --- Netherlands ---
        "ziggo.nl",
        "kpnmail.nl",
        "planet.nl",
        "home.nl",
        "xs4all.nl",
        "hetnet.nl",
        # --- Nordics ---
        "telia.com",
        "telia.se",
        "spray.se",
        "online.no",
        "mail.dk",
        "elisa.fi",
        "suomi24.fi",
        # --- UK / Ireland ---
        "btinternet.com",
        "btopenworld.com",
        "sky.com",
        "talktalk.net",
        "virginmedia.com",
        "blueyonder.co.uk",
        "ntlworld.com",
        "tiscali.co.uk",
        "eircom.net",
        # --- Poland / Czechia / Central & Eastern Europe ---
        "wp.pl",
        "o2.pl",
        "onet.pl",
        "onet.eu",
        "interia.pl",
        "interia.eu",
        "op.pl",
        "vp.pl",
        "gazeta.pl",
        "seznam.cz",
        "email.cz",
        "post.cz",
        "centrum.cz",
        "centrum.sk",
        "azet.sk",
        "freemail.hu",
        "citromail.hu",
        "abv.bg",
        "mail.bg",
        "dir.bg",
        # --- Turkey / Middle East / Africa ---
        "mynet.com",
        "superonline.com",
        "walla.co.il",
        "maktoob.com",
        "webmail.co.za",
        "mweb.co.za",
        "vodamail.co.za",
        # --- Latin America ---
        "bol.com.br",
        "uol.com.br",
        "terra.com.br",
        "ig.com.br",
        "globo.com",
        "globomail.com",
        "zipmail.com.br",
        "r7.com",
        "terra.com",
        "terra.com.mx",
        "terra.com.ar",
        "prodigy.net.mx",
        "ciudad.com.ar",
        "fibertel.com.ar",
        "speedy.com.ar",
        # --- North America ISPs ---
        "comcast.net",
        "xfinity.com",
        "verizon.net",
        "att.net",
        "sbcglobal.net",
        "bellsouth.net",
        "cox.net",
        "charter.net",
        "earthlink.net",
        "juno.com",
        "netzero.net",
        "frontier.com",
        "windstream.net",
        "centurylink.net",
        "rogers.com",
        "bell.net",
        "sympatico.ca",
        "shaw.ca",
        "telus.net",
        "videotron.ca",
        # --- Australia / New Zealand ---
        "bigpond.com",
        "bigpond.net.au",
        "optusnet.com.au",
        "iinet.net.au",
        "tpg.com.au",
        "internode.on.net",
        "westnet.com.au",
        "xtra.co.nz",
    }
)
