# Generated by Django 5.2.10 on 2026-02-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_person_model_and_hunter_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='webhook_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
