# Generated by Django 5.2.13 on 2026-07-20 19:48
"""Backfill webhook_secret for existing Shopify integrations.

The Shopify OAuth callback historically never stored a webhook secret,
so HMAC validation failed for every real Shopify webhook. Webhooks
created via the Admin API are signed with the app's client secret
(``SHOPIFY_CLIENT_SECRET``), so backfill it into integrations that have
an empty ``webhook_secret``. Idempotent: only rows with an empty secret
are touched, and the migration is a no-op if the setting is unset.
"""

from django.conf import settings
from django.db import migrations


def backfill_shopify_webhook_secret(apps, schema_editor):
    """Set webhook_secret on Shopify integrations missing one."""
    client_secret = getattr(settings, "SHOPIFY_CLIENT_SECRET", "")
    if not client_secret:
        return

    integration_model = apps.get_model("core", "Integration")
    integration_model.objects.filter(
        integration_type="shopify",
        webhook_secret="",
    ).update(webhook_secret=client_secret)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_add_webhook_verified_at"),
    ]

    operations = [
        migrations.RunPython(
            backfill_shopify_webhook_secret,
            migrations.RunPython.noop,
        ),
    ]
