# Generated by Django 5.2.13 on 2026-07-20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_add_webhook_verified_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
