# Generated by Django 5.2.13 on 2026-07-20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_backfill_shopify_webhook_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="subscription_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("trial", "Trial"),
                    ("suspended", "Suspended"),
                    ("past_due", "Past Due"),
                    ("cancelled", "Cancelled"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
