# Generated by Django 5.2.16 on 2026-07-21 05:42

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_stripe_subscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='domain',
            field=models.CharField(max_length=255, unique=True, validators=[core.models._validate_domain_for_field]),
        ),
        migrations.AlterField(
            model_name='usagelimit',
            name='plan',
            field=models.CharField(choices=[('free', 'Free Plan'), ('basic', 'Basic Plan'), ('pro', 'Pro Plan'), ('enterprise', 'Enterprise Plan')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free Plan'), ('basic', 'Basic Plan'), ('pro', 'Pro Plan'), ('enterprise', 'Enterprise Plan')], default='free', max_length=100),
        ),
    ]
