# Generated by Django 5.2.16 on 2026-07-21 07:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_prices_from_plan_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='webauthnchallenge',
            index=models.Index(fields=['created_at', 'challenge_type'], name='core_webauthn_created_idx'),
        ),
    ]
