# Generated by Django 5.2.16 on 2026-07-21 07:14

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_index_challenge_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalbillingintegration',
            name='oauth_credentials',
            field=core.fields.EncryptedJSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='globalbillingintegration',
            name='webhook_secret',
            field=core.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='integration',
            name='oauth_credentials',
            field=core.fields.EncryptedJSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='integration',
            name='webhook_secret',
            field=core.fields.EncryptedTextField(blank=True, default=''),
        ),
    ]
