# Generated by Django 5.2.16 on 2026-07-21 10:13
"""Enforce at most one pending invitation per (workspace, email).

Adds a conditional unique constraint covering invitations that have not
been accepted (``accepted_at IS NULL``). Accepted invitations are kept as
history and never block re-inviting the same address. Migration 0028
deduplicated existing pending invitations so this constraint applies
cleanly.
"""

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_dedupe_pending_invitations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="workspaceinvitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("accepted_at__isnull", True)),
                fields=("workspace", "email"),
                name="uniq_pending_invite_workspace_email",
            ),
        ),
    ]
