# Generated by Django 5.2.16 on 2026-07-21 10:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_dedupe_pending_invitations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workspaceinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('accepted_at__isnull', True)), fields=('workspace', 'email'), name='uniq_pending_invite_workspace_email'),
        ),
    ]
