# Generated by Django 5.2.16 on 2026-07-23 09:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_add_pending_invitation_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='grace_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=4),
        ),
    ]
