# Generated by Django 5.2.16 on 2026-07-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_plan_grace_multiplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="ga4_client_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
