# Generated by Django 5.2.16 on 2026-07-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_add_telegram_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='integration_type',
            field=models.CharField(choices=[('stripe_customer', 'Stripe Customer Payments'), ('shopify', 'Shopify Ecommerce'), ('chargify', 'Chargify / Maxio Advanced Billing'), ('slack_notifications', 'Slack Notifications'), ('telegram_notifications', 'Telegram Notifications'), ('teams_notifications', 'Microsoft Teams Notifications'), ('hunter_enrichment', 'Hunter.io Email Enrichment')], max_length=50),
        ),
    ]
