# Generated by Django 5.2.17 on 2026-08-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_add_teams_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='onboarding_nudge_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
