# Generated by Django 5.2.17 on 2026-08-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_purge_shopify_access_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='first_delivery_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
